version: "3.9"

services:
  sec-design:
    image: postgres:16
    container_name: sec-design
    restart: unless-stopped

    environment:
      POSTGRES_USER: sec-design
      POSTGRES_PASSWORD: sec-design
      POSTGRES_DB: sec-design

    ports:
      - "5432:5432"

    volumes:
      - sec-design:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sec-design -d sec-design"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sec-design: